# Generated by Django 4.2.9 on 2024-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0003_delete_newfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrestaurant',
            name='description',
            field=models.CharField(default='Mad', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodtype',
            name='food_type',
            field=models.CharField(choices=[('burger', 'Burger'), ('kebab', 'Kebab'), ('pizza', 'Pizza'), ('salat', 'Salat'), ('asiatisk', 'Asiatisk'), ('japansk', 'Japansk'), ('kinesisk', 'Kinesisk'), ('mexicansk', 'Mexicansk'), ('thai', 'Thai'), ('middelhavskøkken', 'Middelhavskøkken'), ('sandwich', 'Sandwich'), ('sushi', 'Sushi'), ('andet', 'Andet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newrestaurant',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newrestaurant',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
