# Generated by Django 4.2.9 on 2024-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0005_newcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrestaurant',
            name='FoodType',
        ),
        migrations.AddField(
            model_name='newrestaurant',
            name='categories',
            field=models.ManyToManyField(to='Japa.newcategory'),
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
    ]
