# Generated by Django 4.2.9 on 2024-02-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0009_remove_newfood_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newundercategory',
            name='category',
            field=models.ManyToManyField(to='Japa.newcategory'),
        ),
    ]
