# Generated by Django 4.2.9 on 2024-02-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0011_nykategori_nyrestaurant_nytmad_nyunderkategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nyunderkategori',
            name='Restaurant',
        ),
        migrations.AddField(
            model_name='nyunderkategori',
            name='Kategori',
            field=models.ManyToManyField(to='Japa.nykategori'),
        ),
    ]
