# Generated by Django 4.2.9 on 2024-02-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0012_remove_nyunderkategori_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nytmad',
            name='Underkategori',
            field=models.ManyToManyField(to='Japa.nyunderkategori'),
        ),
    ]
