# Generated by Django 4.2.9 on 2024-02-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0013_alter_nytmad_underkategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nytmad',
            name='Beskrivelse',
            field=models.CharField(max_length=200),
        ),
    ]
