# Generated by Django 4.2.10 on 2024-03-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0015_nybestilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='nybestilling',
            name='Accepteret',
            field=models.BooleanField(default=False),
        ),
    ]
