# Generated by Django 4.2.9 on 2024-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('burger', 'Burger'), ('kebab', 'Kebab'), ('pizza', 'Pizza'), ('salat', 'Salat'), ('asiatisk', 'Asiatisk'), ('japansk', 'Japansk'), ('kinesisk', 'Kinesisk'), ('mexicansk', 'Mexicansk'), ('thai', 'Thai'), ('middelhavskøkken', 'Middelhavskøkken'), ('sandwich', 'Sandwich'), ('sushi', 'Sushi'), ('other', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewFood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='food_images')),
            ],
        ),
        migrations.CreateModel(
            name='NewRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('delivery_fee', models.FloatField()),
                ('minimum_order', models.FloatField()),
                ('image', models.ImageField(upload_to='restaurant_images')),
                ('FoodType', models.ManyToManyField(related_name='FoodType', to='Japa.foodtype')),
            ],
        ),
    ]
