# Generated by Django 4.2.9 on 2024-01-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0002_foodtype_newfood_newrestaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFood',
        ),
    ]
