# Generated by Django 4.2.8 on 2024-01-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0004_newrestaurant_description_alter_foodtype_food_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
