# Generated by Django 4.2.9 on 2024-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0007_alter_newrestaurant_description_newfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUnderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('foods', models.ManyToManyField(to='Japa.newfood')),
            ],
        ),
    ]
