# Generated by Django 4.2.9 on 2024-02-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0008_newundercategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newfood',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='newundercategory',
            name='foods',
        ),
        migrations.AddField(
            model_name='newfood',
            name='undercategory',
            field=models.ManyToManyField(to='Japa.newundercategory'),
        ),
    ]
