# Generated by Django 4.2.9 on 2024-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0010_newundercategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NyKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=50)),
                ('Billede', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NyRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
                ('Beskrivelse', models.CharField(max_length=50)),
                ('Åbningstid', models.TimeField()),
                ('Lukketid', models.TimeField()),
                ('Leveringsgebyr', models.FloatField()),
                ('Minimumsordre', models.FloatField()),
                ('Billede', models.BinaryField(blank=True, null=True)),
                ('Kategorier', models.ManyToManyField(to='Japa.nykategori')),
            ],
        ),
        migrations.CreateModel(
            name='NytMad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Billede', models.BinaryField(blank=True, null=True)),
                ('Navn', models.CharField(max_length=50)),
                ('Beskrivelse', models.CharField(max_length=50)),
                ('Pris', models.FloatField()),
                ('Underkategori', models.ManyToManyField(to='Japa.nykategori')),
            ],
        ),
        migrations.CreateModel(
            name='NyUnderkategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Navn', models.CharField(max_length=50)),
                ('Restaurant', models.ManyToManyField(to='Japa.nyrestaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='newfood',
            name='undercategory',
        ),
        migrations.RemoveField(
            model_name='newrestaurant',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='newundercategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewCategory',
        ),
        migrations.DeleteModel(
            name='NewFood',
        ),
        migrations.DeleteModel(
            name='NewRestaurant',
        ),
        migrations.DeleteModel(
            name='NewUnderCategory',
        ),
    ]
