# Generated by Django 4.2.9 on 2024-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0017_alter_nybestilling_leverings_tid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nybestilling',
            name='Mad',
        ),
        migrations.AddField(
            model_name='nybestilling',
            name='Mad',
            field=models.TextField(default='[]'),
        ),
    ]
