# Generated by Django 4.2.9 on 2024-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0018_remove_nybestilling_mad_nybestilling_mad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nybestilling',
            name='Leveringsadresse_type',
            field=models.TextField(),
        ),
    ]
