# Generated by Django 4.2.9 on 2024-03-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0019_alter_nybestilling_leveringsadresse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nybestilling',
            name='Leveringsadresse_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('office', 'Office'), ('other', 'Other')], default='house', max_length=20),
        ),
    ]
