# Generated by Django 4.2.9 on 2024-03-04 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0020_alter_nybestilling_leveringsadresse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_courier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nybestilling',
            name='Courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nybestilling',
            name='Restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
