# Generated by Django 4.2.9 on 2024-03-04 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0021_customuser_is_courier_customuser_is_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nybestilling',
            old_name='Courier',
            new_name='IsCourier',
        ),
        migrations.AddField(
            model_name='nybestilling',
            name='IsRestaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nybestilling',
            name='Restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Japa.nyrestaurant'),
        ),
    ]
