# Generated by Django 4.2.9 on 2024-03-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Japa', '0022_rename_courier_nybestilling_iscourier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nybestilling',
            old_name='IsCourier',
            new_name='Courier',
        ),
        migrations.RemoveField(
            model_name='nybestilling',
            name='IsRestaurant',
        ),
    ]
